import { 
  Room, 
  Faculty, 
  Batch, 
  BatchMergeGroup, 
  Course, 
  ClassSession, 
  Semester, 
  SemesterCalendarEvent, 
  Student, 
  StudentCourseCompleted, 
  AdvisingSuggestion, 
  AuditLogEntry, 
  TimetableVersion,
  MakeupRequest
} from '@/types';

export const INITIAL_SEMESTERS: Semester[] = [
  {
    id: 'sem-fall-2026',
    name: 'Fall 2026',
    academic_year: '2026-2027',
    start_date: '2026-09-01',
    end_date: '2027-01-20',
    is_active: true,
  },
  {
    id: 'sem-spring-2027',
    name: 'Spring 2027',
    academic_year: '2026-2027',
    start_date: '2027-02-01',
    end_date: '2027-06-25',
    is_active: false,
  },
];

export const INITIAL_CALENDAR: SemesterCalendarEvent[] = [
  {
    id: 'cal-midterm-2026',
    semester_id: 'sem-fall-2026',
    event_name: 'Midterm Examination Week',
    event_type: 'midterm_week',
    start_date: '2026-10-26',
    end_date: '2026-10-31',
    description: 'Regular classes suspended for campus midterms',
  },
  {
    id: 'cal-holiday-2026',
    semester_id: 'sem-fall-2026',
    event_name: 'Fall Break & National Holiday',
    event_type: 'holiday',
    start_date: '2026-11-20',
    end_date: '2026-11-22',
    description: 'Campus closed for public holidays',
  },
  {
    id: 'cal-finals-2026',
    semester_id: 'sem-fall-2026',
    event_name: 'Final Examination Period',
    event_type: 'finals_week',
    start_date: '2027-01-10',
    end_date: '2027-01-20',
    description: 'Final examinations scheduled across departments',
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-101',
    name: 'Hall 101',
    building: 'Academic Block A',
    floor: 1,
    capacity: 60,
    room_types: ['standard', 'multimedia'],
  },
  {
    id: 'room-102',
    name: 'Hall 102',
    building: 'Academic Block A',
    floor: 1,
    capacity: 55,
    room_types: ['standard'],
  },
  {
    id: 'room-201',
    name: 'Horseshoe Amphitheater 201',
    building: 'Academic Block A',
    floor: 2,
    capacity: 75,
    room_types: ['horseshoe', 'multimedia', 'interactive_lcd'],
  },
  {
    id: 'room-202',
    name: 'Smart Classroom 202',
    building: 'Academic Block A',
    floor: 2,
    capacity: 45,
    room_types: ['interactive_lcd', 'multimedia'],
  },
  {
    id: 'room-301',
    name: 'CS Lab 301',
    building: 'Computing Center',
    floor: 3,
    capacity: 40,
    room_types: ['computer_lab', 'multimedia'],
  },
  {
    id: 'room-302',
    name: 'AI & Data Lab 302',
    building: 'Computing Center',
    floor: 3,
    capacity: 40,
    room_types: ['computer_lab', 'multimedia', 'interactive_lcd'],
  },
  {
    id: 'room-401',
    name: 'Seminar Hall 401',
    building: 'Executive Tower',
    floor: 4,
    capacity: 120,
    room_types: ['horseshoe', 'multimedia', 'interactive_lcd'],
  },
  {
    id: 'room-105',
    name: 'Room 105',
    building: 'Engineering Wing',
    floor: 1,
    capacity: 50,
    room_types: ['standard', 'multimedia'],
  },
];

export const INITIAL_FACULTY: Faculty[] = [
  {
    id: 'fac-turing',
    name: 'Dr. Alan Turing',
    email: 'alan.turing@univ.edu',
    department: 'Computer Science',
    max_load_per_day: 3,
    availability_window: {
      mon: ['08:30-17:00'],
      tue: ['08:30-17:00'],
      wed: ['08:30-17:00'],
      thu: ['08:30-17:00'],
      fri: ['08:30-13:00'],
    },
  },
  {
    id: 'fac-lovelace',
    name: 'Prof. Ada Lovelace',
    email: 'ada.lovelace@univ.edu',
    department: 'Software Engineering',
    max_load_per_day: 4,
    availability_window: {
      mon: ['08:30-17:00'],
      tue: ['08:30-17:00'],
      wed: ['08:30-17:00'],
      thu: ['08:30-17:00'],
      fri: ['08:30-17:00'],
    },
  },
  {
    id: 'fac-shannon',
    name: 'Dr. Claude Shannon',
    email: 'claude.shannon@univ.edu',
    department: 'Computer Science',
    max_load_per_day: 3,
    availability_window: {
      mon: ['10:00-17:00'],
      wed: ['10:00-17:00'],
      fri: ['10:00-17:00'],
    },
  },
  {
    id: 'fac-hopper',
    name: 'Dr. Grace Hopper',
    email: 'grace.hopper@univ.edu',
    department: 'Computer Science',
    max_load_per_day: 4,
    availability_window: {
      mon: ['08:30-17:00'],
      tue: ['08:30-17:00'],
      wed: ['08:30-17:00'],
      thu: ['08:30-17:00'],
      fri: ['08:30-17:00'],
    },
  },
  {
    id: 'fac-neumann',
    name: 'Prof. John von Neumann',
    email: 'john.neumann@univ.edu',
    department: 'Mathematics & AI',
    max_load_per_day: 3,
    availability_window: {
      tue: ['08:30-17:00'],
      thu: ['08:30-17:00'],
      fri: ['08:30-17:00'],
    },
  },
  {
    id: 'fac-hamilton',
    name: 'Dr. Margaret Hamilton',
    email: 'margaret.h@univ.edu',
    department: 'Software Engineering',
    max_load_per_day: 4,
    availability_window: {
      mon: ['08:30-17:00'],
      tue: ['08:30-17:00'],
      wed: ['08:30-17:00'],
      thu: ['08:30-17:00'],
      fri: ['08:30-17:00'],
    },
  },
  {
    id: 'fac-liskov',
    name: 'Dr. Barbara Liskov',
    email: 'barbara.liskov@univ.edu',
    department: 'Information Systems',
    max_load_per_day: 3,
    availability_window: {
      mon: ['08:30-14:00'],
      wed: ['08:30-14:00'],
      thu: ['08:30-14:00'],
    },
  },
];

export const INITIAL_MERGE_GROUPS: BatchMergeGroup[] = [
  {
    id: 'mg-joint-ethics',
    name: 'Joint CS/SE Ethics & Professional Practices',
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch-cs-2024-a',
    name: 'BSCS-2024-A',
    program: 'Computer Science',
    semester: 5,
    student_count: 45,
    is_irregular: false,
    merge_group_id: 'mg-joint-ethics',
  },
  {
    id: 'batch-cs-2024-b',
    name: 'BSCS-2024-B',
    program: 'Computer Science',
    semester: 5,
    student_count: 42,
    is_irregular: false,
  },
  {
    id: 'batch-se-2024-a',
    name: 'BSSE-2024-A',
    program: 'Software Engineering',
    semester: 5,
    student_count: 40,
    is_irregular: false,
    merge_group_id: 'mg-joint-ethics',
  },
  {
    id: 'batch-ai-2025-a',
    name: 'BSAI-2025-A',
    program: 'Artificial Intelligence',
    semester: 3,
    student_count: 38,
    is_irregular: false,
  },
  {
    id: 'batch-cs-freshmen',
    name: 'BSCS-2026-Freshmen',
    program: 'Computer Science',
    semester: 1,
    student_count: 50,
    is_irregular: false,
  },
  {
    id: 'batch-irregular-fall26',
    name: 'IRREG-Fall26-Special',
    program: 'Computer Science (Irregular)',
    semester: 5,
    student_count: 12,
    is_irregular: true,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-cs101',
    code: 'CS-101',
    name: 'Introduction to Computing',
    department: 'Computer Science',
    credit_hours: 3,
    required_room_types: ['standard'],
    prerequisites: [],
  },
  {
    id: 'crs-cs201',
    code: 'CS-201',
    name: 'Data Structures & Algorithms',
    department: 'Computer Science',
    credit_hours: 4,
    required_room_types: ['computer_lab', 'multimedia'],
    prerequisites: ['crs-cs101'],
  },
  {
    id: 'crs-cs301',
    code: 'CS-301',
    name: 'Database Systems',
    department: 'Computer Science',
    credit_hours: 3,
    required_room_types: ['multimedia'],
    prerequisites: ['crs-cs201'],
  },
  {
    id: 'crs-se302',
    code: 'SE-302',
    name: 'Software Architecture & Design',
    department: 'Software Engineering',
    credit_hours: 3,
    required_room_types: ['multimedia', 'interactive_lcd'],
    prerequisites: ['crs-cs201'],
  },
  {
    id: 'crs-ai401',
    code: 'AI-401',
    name: 'Machine Learning & Deep Neural Nets',
    department: 'Artificial Intelligence',
    credit_hours: 4,
    required_room_types: ['computer_lab', 'multimedia'],
    prerequisites: ['crs-cs201'],
  },
  {
    id: 'crs-cs305',
    code: 'CS-305',
    name: 'Computer Networks & Security',
    department: 'Computer Science',
    credit_hours: 3,
    required_room_types: ['multimedia'],
    prerequisites: ['crs-cs101'],
  },
  {
    id: 'crs-hum201',
    code: 'HUM-201',
    name: 'Professional Ethics & Law',
    department: 'Humanities',
    credit_hours: 2,
    required_room_types: ['standard', 'horseshoe'],
    prerequisites: [],
  },
  {
    id: 'crs-cs401',
    code: 'CS-401',
    name: 'Cloud Computing & Distributed Systems',
    department: 'Computer Science',
    credit_hours: 3,
    required_room_types: ['multimedia'],
    prerequisites: ['crs-cs305'],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-hamza',
    roll_number: 'BCS-2024-001',
    name: 'Hamza Tariq',
    email: 'hamza.t@student.univ.edu',
    batch_id: 'batch-cs-2024-a',
    is_irregular: false,
  },
  {
    id: 'std-zainab',
    roll_number: 'BCS-2024-045',
    name: 'Zainab Fatima',
    email: 'zainab.f@student.univ.edu',
    batch_id: 'batch-cs-2024-a',
    is_irregular: false,
  },
  {
    id: 'std-bilal-irreg',
    roll_number: 'IRR-2023-019',
    name: 'Bilal Ahmed (Irregular/Transfer)',
    email: 'bilal.a@student.univ.edu',
    batch_id: 'batch-irregular-fall26',
    is_irregular: true,
  },
];

export const INITIAL_COMPLETED_COURSES: StudentCourseCompleted[] = [
  {
    id: 'scc-1',
    student_id: 'std-hamza',
    course_id: 'crs-cs101',
    grade: 'A',
    semester_completed: 'Spring 2025',
  },
  {
    id: 'scc-2',
    student_id: 'std-hamza',
    course_id: 'crs-cs201',
    grade: 'B+',
    semester_completed: 'Fall 2025',
  },
  {
    id: 'scc-3',
    student_id: 'std-bilal-irreg',
    course_id: 'crs-cs101',
    grade: 'B',
    semester_completed: 'Fall 2024',
  },
];

export const INITIAL_SESSIONS: ClassSession[] = [
  // Monday
  {
    id: 'sess-1',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-cs301',
    faculty_id: 'fac-turing',
    room_id: 'room-101',
    batch_id: 'batch-cs-2024-a',
    batch_group_id: null,
    day_of_week: 1, // Mon
    start_time: '08:30',
    end_time: '10:00',
    session_type: 'regular',
    status: 'published',
  },
  {
    id: 'sess-2',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-cs201',
    faculty_id: 'fac-hopper',
    room_id: 'room-301',
    batch_id: 'batch-cs-2024-a',
    batch_group_id: null,
    day_of_week: 1, // Mon
    start_time: '10:15', // 15 min buffer after 10:00
    end_time: '11:45',
    session_type: 'regular',
    status: 'published',
  },
  {
    id: 'sess-3',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-cs305',
    faculty_id: 'fac-shannon',
    room_id: 'room-105',
    batch_id: 'batch-cs-2024-b',
    batch_group_id: null,
    day_of_week: 1, // Mon
    start_time: '10:15',
    end_time: '11:45',
    session_type: 'regular',
    status: 'published',
  },
  // Tuesday
  {
    id: 'sess-4',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-se302',
    faculty_id: 'fac-lovelace',
    room_id: 'room-202',
    batch_id: 'batch-se-2024-a',
    batch_group_id: null,
    day_of_week: 2, // Tue
    start_time: '09:00',
    end_time: '10:30',
    session_type: 'regular',
    status: 'published',
  },
  {
    id: 'sess-5',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-ai401',
    faculty_id: 'fac-neumann',
    room_id: 'room-302',
    batch_id: 'batch-ai-2025-a',
    batch_group_id: null,
    day_of_week: 2, // Tue
    start_time: '11:00',
    end_time: '12:30',
    session_type: 'regular',
    status: 'published',
  },
  // Wednesday (Merged Session in Horseshoe Hall)
  {
    id: 'sess-6a',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-hum201',
    faculty_id: 'fac-liskov',
    room_id: 'room-201',
    batch_id: 'batch-cs-2024-a',
    batch_group_id: 'mg-joint-ethics',
    day_of_week: 3, // Wed
    start_time: '13:00',
    end_time: '14:30',
    session_type: 'regular',
    status: 'published',
  },
  {
    id: 'sess-6b',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-hum201',
    faculty_id: 'fac-liskov',
    room_id: 'room-201',
    batch_id: 'batch-se-2024-a',
    batch_group_id: 'mg-joint-ethics',
    day_of_week: 3, // Wed
    start_time: '13:00',
    end_time: '14:30',
    session_type: 'regular',
    status: 'published',
  },
  // Thursday Draft Session
  {
    id: 'sess-7',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-cs401',
    faculty_id: 'fac-hamilton',
    room_id: 'room-101',
    batch_id: 'batch-cs-2024-a',
    batch_group_id: null,
    day_of_week: 4, // Thu
    start_time: '10:00',
    end_time: '11:30',
    session_type: 'regular',
    status: 'draft',
  },
];

export const INITIAL_ADVISING_SUGGESTIONS: AdvisingSuggestion[] = [
  {
    id: 'adv-1',
    student_id: 'std-bilal-irreg',
    flagged_course_id: 'crs-cs301',
    clashing_course_id: null,
    reason: 'Prerequisite Unfulfilled: Student Bilal Ahmed has not completed CS-201 (Data Structures). Cannot enroll in CS-301.',
    suggested_alternative: {
      action: 'enroll_prerequisite',
      recommended_course: 'crs-cs201',
      alternative_slots: [{ day: 1, start: '10:15', end: '11:45', room: 'CS Lab 301' }],
    },
    status: 'pending',
    notes: 'Coordinator review required: Swap CS-301 for CS-201 repeat slot.',
    created_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'adv-2',
    student_id: 'std-bilal-irreg',
    flagged_course_id: 'crs-cs305',
    clashing_course_id: 'crs-se302',
    reason: 'Elective Cross-Batch Clash: Student desired elective CS-305 overlaps with required department core SE-302 on Tuesday.',
    suggested_alternative: {
      action: 'shift_slot',
      available_faculty_slots: [{ day: 4, start: '14:00', end: '15:30', faculty: 'Dr. Claude Shannon' }],
    },
    status: 'pending',
    notes: 'Suggested shift: Move CS-305 elective to Thursday afternoon where Dr. Shannon is free.',
    created_at: '2026-09-08T10:30:00Z',
  },
];

export const INITIAL_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'log-1',
    class_session_id: 'sess-1',
    changed_by: 'Admin Coordinator',
    change_type: 'INSERT',
    new_value: { course_id: 'crs-cs301', start_time: '08:30', end_time: '10:00' },
    description: 'Scheduled CS-301 for BSCS-2024-A in Hall 101',
    timestamp: '2026-09-08T09:00:00Z',
  },
  {
    id: 'log-2',
    class_session_id: 'sess-7',
    changed_by: 'Coordinator Sarah',
    change_type: 'INSERT',
    new_value: { course_id: 'crs-cs401', start_time: '10:00', end_time: '11:30' },
    description: 'Created draft session for CS-401 Cloud Computing',
    timestamp: '2026-09-08T11:15:00Z',
  },
];

export const INITIAL_MAKEUP_REQUESTS: MakeupRequest[] = [
  {
    id: 'mup-1',
    semester_id: 'sem-fall-2026',
    course_id: 'crs-cs201',
    faculty_id: 'fac-hopper',
    room_id: 'room-301',
    batch_id: 'batch-cs-2024-a',
    requested_date: '2026-09-19',
    start_time: '14:00',
    end_time: '15:30',
    reason: 'Lab adjustment for missed class due to faculty conference',
    status: 'pending',
    requested_by: 'Dr. Grace Hopper',
    created_at: '2026-09-08T12:00:00Z',
  },
];
